#%RAML 1.0 NamedExample

value:
  [ 
    {
      "ID": 101,
      "airline": "AirIndia",
      "flightCode": "AI101",
      "fromAirportCode": "HYD",
      "toAirportCode": "Bang",
      "departureDate": "20-Feb-2020",
      "emptySeats": 0,
      "totalSeats": 200,
      "price": 199,
      "planeType": "AirIndia 737"
    },
    {
      "ID": 102,
      "airline": "AirIndia",
      "flightCode": "AI102",
      "fromAirportCode": "HYD",
      "toAirportCode": "Bang",
      "departureDate": "20-Feb-2020",
      "emptySeats": 24,
      "totalSeats": 350,
      "price": 450,
      "planeType": "AirIndia 747"
    },
    {
      "ID": 103,
      "airline": "AirIndia",
      "flightCode": "AI103",
      "fromAirportCode": "HYD",
      "toAirportCode": "Bang",
      "departureDate": "20-Feb-2020",
      "emptySeats": 33,
      "totalSeats": 400,
      "price": 450,
      "planeType": "AirIndia 757"
    }
  ]